site_name: arc42
nav:
    - Home: 'index.md'
    - 'arc42':
        - '1. Einführung und Ziele': 'arc42/01_introduction_and_goals.md'
        - '2. Randbedingungen': 'arc42/02_architecture_constraints.md'
        - '3. Kontextabgrenzung': 'arc42/03_system_scope_and_context.md'
        - '4. Lösungsstrategie': 'arc42/04_solution_strategy.md'
        - '5. Bausteinsicht': 'arc42/05_building_block_view.md'
        - '6. Laufzeitsicht': 'arc42/06_runtime_view.md'
        - '7. Verteilungssicht': 'arc42/07_deployment_view.md'
        - '8. Querschnittliche Konzepte': 'arc42/08_concepts.md'
        - '9. Architekturentscheidungen': 'arc42/09_architecture_decisions.md'
        - '10. Qualitätsanforderungen': 'arc42/10_quality_requirements.md'
        - '11. Risiken und technische Schulden': 'arc42/11_technical_risks.md'
        - '12. Glossar': 'arc42/12_glossary.md'

    - API:
        - 'OpenAPI': 'openapi.md'
#        - 'Release Notes': 'release-notes.md'

markdown_extensions:

theme:
    name: readthedocs
    locale: de