site_name: arc42
nav:
    - Home: 'index.md'
    - 'arc42':
        - '1. Einführung und Ziele': '01_introduction_and_goals.md'
        - '2. Randbedingungen': '02_architecture_constraints.md'
        - '3. Kontextabgrenzung': '03_system_scope_and_context.md'
        - '4. Lösungsstrategie': '04_solution_strategy.md'
        - '5. Bausteinsicht': '05_building_block_view.md'
        - '6. Laufzeitsicht': '06_runtime_view.md'
        - '7. Verteilungssicht': '07_deployment_view.md'
        - '8. Querschnittliche Konzepte': '08_concepts.md'
        - '9. Architekturentscheidungen': '09_architecture_decisions.md'
        - '10. Qualitätsanforderungen': '10_quality_requirements.md'
        - '11. Risiken und technische Schulden': '11_technical_risks.md'
        - '12. Glossar': '12_glossary.md'

    - API:
        - 'OpenAPI': 'openapi.md'
#        - 'Release Notes': 'release-notes.md'

markdown_extensions:

theme:
    name: readthedocs
    locale: de